pipeline {

    agent any

    environment {
        APP_NAME = "devops-nbd"
        IMAGE = "devops-nbd:v1"
    }

    options {
        timestamps()
        ansiColor('xterm')
    }

    stages {

        stage('Checkout') {
            steps {
                echo "========== CHECKOUT =========="
                checkout scm
            }
        }

        stage('Workspace Information') {
            steps {
                echo "========== WORKSPACE =========="
                sh '''
                pwd
                ls -la
                '''
            }
        }

        stage('Verify Dockerfile') {
            steps {
                echo "========== VERIFY DOCKERFILE =========="
                sh '''
                ls app
                cat app/Dockerfile
                '''
            }
        }

        stage('Git Information') {
            steps {
                echo "========== GIT INFORMATION =========="
                sh '''
                git --version
                git branch
                git log --oneline -5
                '''
            }
        }

        stage('Helm Validation') {
            steps {
                echo "========== HELM LINT =========="
                sh '''
                helm version
                helm lint helm/devops-nbd
                '''
            }
        }

        stage('Helm Manifest Preview') {
            steps {
                echo "========== HELM TEMPLATE =========="
                sh '''
                helm template devops helm/devops-nbd | head -100
                '''
            }
        }

        stage('Kubernetes Validation') {
            steps {
                echo "========== KUBERNETES VALIDATION =========="
                sh '''
                kubectl version --client

                for file in kubernetes/*.yaml
                do
                    echo "Validating $file"
                    kubectl apply --dry-run=client -f $file
                done
                '''
            }
        }

        stage('Pipeline Summary') {
            steps {
                echo '''
==========================================
 Enterprise CI Pipeline Completed
==========================================
 GitHub            : OK
 Jenkins           : OK
 Dockerfile        : OK
 Helm Lint         : OK
 Helm Template     : OK
 Kubernetes YAML   : OK
==========================================
'''
            }
        }
    }

    post {

        success {
            echo "SUCCESS : Enterprise CI Pipeline Passed"
        }

        failure {
            echo "FAILED : Enterprise CI Pipeline Failed"
        }

        always {
            echo "Cleaning Workspace..."
            deleteDir()
        }
    }
}