pipeline {

    agent any

    environment {
        APP_NAME = "devops-nbd"
        IMAGE = "devops-nbd:v1"
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
                checkout scm
            }
        }

        stage('Workspace') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }

        stage('Verify Dockerfile') {
            steps {
                echo 'Dockerfile Verification'
                sh 'ls app'
                sh 'cat app/Dockerfile'
            }
        }

        stage('Helm Validation') {
            steps {
                echo 'Running Helm Lint'
                sh 'helm lint helm/devops-nbd'
            }
        }

        stage('Kubernetes Validation') {
            steps {
                echo 'Validating Kubernetes YAML'

                sh '''
                find kubernetes -name "*.yaml" -exec kubectl apply --dry-run=client -f {} \\;
                '''
            }
        }

        stage('Manifest Preview') {
            steps {
                sh 'helm template devops helm/devops-nbd | head -100'
            }
        }

        stage('Git Information') {
            steps {
                sh 'git branch'
                sh 'git log --oneline -5'
            }
        }

        stage('Finished') {
            steps {
                echo 'Enterprise CI Validation Successful'
            }
        }
    }

    post {

        success {
            echo 'Pipeline SUCCESS'
        }

        failure {
            echo 'Pipeline FAILED'
        }

        always {
            cleanWs()
        }
    }

}